tick_rate = 1.0
frame_rate = 15.0
key_refresh_rate = 0.5
enable_mouse = false
enable_paste = false
prompt_padding = 1

[key_bindings.popup]
"j" = "ScrollDown"
"k" = "ScrollUp"
"Down" = "ScrollDown"
"Up" = "ScrollUp"
"Enter" = "ClosePopup"
"ESC" = "ClosePopup"

[key_bindings.picker]
"q" = "Quit"
"ESC" = "Quit"
"<g><g>" = "ScrollTop"
"G" = "ScrollBottom"
"Home" = "ScrollTop"
"End" = "ScrollBottom"
"?" = "EnterSearchInsertMode"
"/" = "EnterFilterInsertMode"
"j" = "ScrollDown"
"k" = "ScrollUp"
"Down" = "ScrollDown"
"Up" = "ScrollUp"
"l" = "IncrementPage"
"h" = "DecrementPage"
"Left" = "DecrementPage"
"Right" = "IncrementPage"
"r" = "ReloadData"
"Enter" = "ToggleShowCrateInfo"

[key_bindings.search]
"ESC" = "EnterNormal"
"Enter" = "SubmitSearch"

[key_bindings.filter]
"ESC" = "EnterNormal"
"Enter" = "EnterNormal"
