tick_rate = 1.0
frame_rate = 15.0
key_refresh_rate = 0.5
enable_mouse = false
enable_paste = false
prompt_padding = 1

[key_bindings.popup]
"j" = "ScrollDown"
"k" = "ScrollUp"
"Down" = "ScrollDown"
"Up" = "ScrollUp"
"Enter" = "ClosePopup"
"ESC" = "ClosePopup"

[key_bindings.picker_show_crate_info]
"q" = { SwitchMode = "picker_hide_crate_info" }
"ESC" = { SwitchMode = "picker_hide_crate_info" }
"<g><g>" = "ScrollTop"
"G" = "ScrollBottom"
"Home" = "ScrollTop"
"End" = "ScrollBottom"
"?" = { SwitchMode = "search" }
"/" = { SwitchMode = "filter" }
"j" = "ScrollDown"
"k" = "ScrollUp"
"ctrl-j" = "ScrollCrateInfoDown"
"ctrl-k" = "ScrollCrateInfoUp"
"TAB" = { ToggleSortBy = { reload = true, forward = true } }
"Shift-Backtab" = { ToggleSortBy = { reload = true, forward = false } }
"Down" = "ScrollDown"
"Up" = "ScrollUp"
"l" = "IncrementPage"
"h" = "DecrementPage"
"Left" = "DecrementPage"
"Right" = "IncrementPage"
"r" = "ReloadData"
"Enter" = "ToggleShowCrateInfo"
"<g><b>" = "OpenUrlInBrowser"
"<g><Enter>" = "ShowFullCrateInfo"

[key_bindings.picker_hide_crate_info]
"q" = "Quit"
"ESC" = { SwitchMode = "summary" }
"<g><g>" = "ScrollTop"
"G" = "ScrollBottom"
"Home" = "ScrollTop"
"End" = "ScrollBottom"
"?" = { SwitchMode = "search" }
"/" = { SwitchMode = "filter" }
"j" = "ScrollDown"
"k" = "ScrollUp"
"ctrl-j" = "ScrollCrateInfoDown"
"ctrl-k" = "ScrollCrateInfoUp"
"TAB" = { ToggleSortBy = { reload = true, forward = true } }
"Shift-Backtab" = { ToggleSortBy = { reload = true, forward = false } }
"Down" = "ScrollDown"
"Up" = "ScrollUp"
"l" = "IncrementPage"
"h" = "DecrementPage"
"Left" = "DecrementPage"
"Right" = "IncrementPage"
"r" = "ReloadData"
"Enter" = "ToggleShowCrateInfo"
"<g><b>" = "OpenUrlInBrowser"
"<g><Enter>" = "ShowFullCrateInfo"

[key_bindings.summary]
"q" = "Quit"
"ESC" = "Quit"
"?" = { SwitchMode = "search" }
"/" = { SwitchMode = "filter" }

[key_bindings.search]
"TAB" = { ToggleSortBy = { reload = false, forward = true } }
"Shift-Backtab" = { ToggleSortBy = { reload = true, forward = false } }
"ESC" = { SwitchMode = "picker_hide_crate_info" }
"Enter" = "SubmitSearch"

[key_bindings.filter]
"ESC" = { SwitchMode = "picker_hide_crate_info" }
"Enter" = { SwitchMode = "picker_hide_crate_info" }
